name = "request-music"
compatibility_date = "2026-05-08"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "request_music"
database_id = "1650a8f2-72e4-4ebe-8de2-5a5b9ffd6438"
